"""
tools/sector_map.py

Static GICS sector mapping for all tier-1-supported tickers in
ticker_universe. Used by tools/seed_sectors.py to populate the
sector column added in migrations/008_add_ticker_sector.sql.

Generated 2026-05-15 via yfinance Ticker(t).info["sector"].
Re-run tools/generate_sector_map.py to regenerate.

Values must match keys of pipeline.sources.macro.SECTOR_ETFS exactly
(11-class GICS taxonomy). Validation is enforced at import time below.
"""
from __future__ import annotations

TICKER_SECTORS: dict[str, str] = {
    "A": "Health Care",
    "AA": "Materials",
    "AAL": "Industrials",
    "AAPL": "Information Technology",
    "ABBV": "Health Care",
    "ABC": "Health Care",
    "ABT": "Health Care",
    "ACM": "Industrials",
    "ACN": "Information Technology",
    "ADBE": "Information Technology",
    "ADI": "Information Technology",
    "ADM": "Consumer Staples",
    "ADP": "Information Technology",
    "AEP": "Utilities",
    "AES": "Utilities",
    "AFL": "Financials",
    "AGCO": "Industrials",
    "AIG": "Financials",
    "AKAM": "Information Technology",
    "AL": "Industrials",
    "ALB": "Materials",
    "ALGN": "Health Care",
    "ALK": "Industrials",
    "ALL": "Financials",
    "ALLE": "Industrials",
    "ALLY": "Financials",
    "AMAT": "Information Technology",
    "AMCR": "Consumer Discretionary",
    "AMD": "Information Technology",
    "AME": "Industrials",
    "AMED": "Health Care",
    "AMG": "Financials",
    "AMGN": "Health Care",
    "AMP": "Financials",
    "AMT": "Real Estate",
    "AMZN": "Consumer Discretionary",
    "ANET": "Information Technology",
    "ANSS": "Information Technology",
    "AON": "Financials",
    "AOS": "Industrials",
    "APA": "Energy",
    "APD": "Materials",
    "APH": "Information Technology",
    "APTV": "Consumer Discretionary",
    "ARE": "Real Estate",
    "ATI": "Industrials",
    "AVB": "Real Estate",
    "AVGO": "Information Technology",
    "AVY": "Consumer Discretionary",
    "AWK": "Utilities",
    "AWR": "Utilities",
    "AXON": "Industrials",
    "AXP": "Financials",
    "AZO": "Consumer Discretionary",
    "BA": "Industrials",
    "BAC": "Financials",
    "BALL": "Consumer Discretionary",
    "BAX": "Health Care",
    "BBWI": "Consumer Discretionary",
    "BDX": "Health Care",
    "BEN": "Financials",
    "BG": "Consumer Staples",
    "BIIB": "Health Care",
    "BK": "Financials",
    "BKNG": "Consumer Discretionary",
    "BKR": "Energy",
    "BLK": "Financials",
    "BLKB": "Information Technology",
    "BMY": "Health Care",
    "BRK.B": "Financials",
    "BSX": "Health Care",
    "BWA": "Consumer Discretionary",
    "BXP": "Real Estate",
    "C": "Financials",
    "CACC": "Financials",
    "CAG": "Consumer Staples",
    "CAH": "Health Care",
    "CARR": "Industrials",
    "CAT": "Industrials",
    "CB": "Financials",
    "CBOE": "Financials",
    "CCI": "Real Estate",
    "CCL": "Consumer Discretionary",
    "CDNS": "Information Technology",
    "CDW": "Information Technology",
    "CE": "Materials",
    "CEG": "Utilities",
    "CF": "Materials",
    "CFG": "Financials",
    "CHD": "Consumer Staples",
    "CHRW": "Industrials",
    "CHTR": "Communication Services",
    "CI": "Health Care",
    "CINF": "Financials",
    "CL": "Consumer Staples",
    "CLX": "Consumer Staples",
    "CMC": "Industrials",
    "CMCSA": "Communication Services",
    "CME": "Financials",
    "CMG": "Consumer Discretionary",
    "CMS": "Utilities",
    "CNC": "Health Care",
    "CNH": "Industrials",
    "COF": "Financials",
    "COO": "Health Care",
    "COP": "Energy",
    "COST": "Consumer Staples",
    "COTY": "Consumer Staples",
    "CPB": "Consumer Staples",
    "CPRI": "Consumer Discretionary",
    "CPRT": "Industrials",
    "CPT": "Real Estate",
    "CRH": "Materials",
    "CRM": "Information Technology",
    "CRWD": "Information Technology",
    "CSCO": "Information Technology",
    "CSX": "Industrials",
    "CTAS": "Industrials",
    "CTRA": "Energy",
    "CTSH": "Information Technology",
    "CUBE": "Real Estate",
    "CVS": "Health Care",
    "CVX": "Energy",
    "CZR": "Consumer Discretionary",
    "D": "Utilities",
    "DAL": "Industrials",
    "DDOG": "Information Technology",
    "DE": "Industrials",
    "DELL": "Information Technology",
    "DFS": "Financials",
    "DHI": "Consumer Discretionary",
    "DHR": "Health Care",
    "DIS": "Communication Services",
    "DKNG": "Consumer Discretionary",
    "DLR": "Real Estate",
    "DLTR": "Consumer Staples",
    "DOV": "Industrials",
    "DPZ": "Consumer Discretionary",
    "DTE": "Utilities",
    "DUK": "Utilities",
    "DVA": "Health Care",
    "DVN": "Energy",
    "DXC": "Information Technology",
    "DXCM": "Health Care",
    "EA": "Communication Services",
    "EBAY": "Consumer Discretionary",
    "ECL": "Materials",
    "ED": "Utilities",
    "EFX": "Industrials",
    "EG": "Financials",
    "EGP": "Real Estate",
    "EL": "Consumer Staples",
    "ELS": "Real Estate",
    "ELV": "Health Care",
    "EMN": "Materials",
    "EMR": "Industrials",
    "ENPH": "Information Technology",
    "EOG": "Energy",
    "EPAM": "Information Technology",
    "EQIX": "Real Estate",
    "EQR": "Real Estate",
    "EQT": "Energy",
    "ES": "Utilities",
    "ESS": "Real Estate",
    "ETN": "Industrials",
    "ETR": "Utilities",
    "ETSY": "Consumer Discretionary",
    "EVRG": "Utilities",
    "EW": "Health Care",
    "EXAS": "Health Care",
    "EXC": "Utilities",
    "EXP": "Materials",
    "EXPD": "Industrials",
    "EXPE": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "FANG": "Energy",
    "FAST": "Industrials",
    "FCX": "Materials",
    "FDX": "Industrials",
    "FE": "Utilities",
    "FFIV": "Information Technology",
    "FHI": "Financials",
    "FI": "Information Technology",
    "FIS": "Information Technology",
    "FISV": "Information Technology",
    "FITB": "Financials",
    "FLS": "Industrials",
    "FMC": "Materials",
    "FOX": "Communication Services",
    "FOXA": "Communication Services",
    "FR": "Real Estate",
    "FRT": "Real Estate",
    "FSLR": "Information Technology",
    "FTNT": "Information Technology",
    "FTV": "Information Technology",
    "GD": "Industrials",
    "GDDY": "Information Technology",
    "GE": "Industrials",
    "GEHC": "Health Care",
    "GILD": "Health Care",
    "GIS": "Consumer Staples",
    "GLW": "Information Technology",
    "GM": "Consumer Discretionary",
    "GNRC": "Industrials",
    "GOOG": "Communication Services",
    "GOOGL": "Communication Services",
    "GPN": "Industrials",
    "GRMN": "Information Technology",
    "GS": "Financials",
    "GWW": "Industrials",
    "H": "Consumer Discretionary",
    "HAL": "Energy",
    "HAS": "Consumer Discretionary",
    "HBAN": "Financials",
    "HCA": "Health Care",
    "HD": "Consumer Discretionary",
    "HES": "Energy",
    "HIG": "Financials",
    "HII": "Industrials",
    "HLT": "Consumer Discretionary",
    "HOLX": "Health Care",
    "HON": "Industrials",
    "HPE": "Information Technology",
    "HPQ": "Information Technology",
    "HRL": "Consumer Staples",
    "HSIC": "Health Care",
    "HSY": "Consumer Staples",
    "HUBB": "Industrials",
    "HUM": "Health Care",
    "HUN": "Materials",
    "HWM": "Industrials",
    "IBM": "Information Technology",
    "ICE": "Financials",
    "IDXX": "Health Care",
    "IEX": "Industrials",
    "IFF": "Materials",
    "ILMN": "Health Care",
    "INCY": "Health Care",
    "INTC": "Information Technology",
    "INTU": "Information Technology",
    "IP": "Consumer Discretionary",
    "IPG": "Communication Services",
    "IQV": "Health Care",
    "IR": "Industrials",
    "ISRG": "Health Care",
    "ITW": "Industrials",
    "IVZ": "Financials",
    "J": "Industrials",
    "JBHT": "Industrials",
    "JNJ": "Health Care",
    "JNPR": "Information Technology",
    "JPM": "Financials",
    "K": "Consumer Staples",
    "KDP": "Consumer Staples",
    "KEY": "Financials",
    "KEYS": "Information Technology",
    "KHC": "Consumer Staples",
    "KIM": "Real Estate",
    "KLAC": "Information Technology",
    "KMB": "Consumer Staples",
    "KMI": "Energy",
    "KO": "Consumer Staples",
    "LDOS": "Information Technology",
    "LEG": "Consumer Discretionary",
    "LEN": "Consumer Discretionary",
    "LHX": "Industrials",
    "LIN": "Materials",
    "LKQ": "Consumer Discretionary",
    "LLY": "Health Care",
    "LMT": "Industrials",
    "LNG": "Energy",
    "LNT": "Utilities",
    "LOW": "Consumer Discretionary",
    "LPLA": "Financials",
    "LRCX": "Information Technology",
    "LSI": "Real Estate",
    "LUV": "Industrials",
    "LVS": "Consumer Discretionary",
    "LYV": "Communication Services",
    "MA": "Financials",
    "MAA": "Real Estate",
    "MAR": "Consumer Discretionary",
    "MAT": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "MCHP": "Information Technology",
    "MCK": "Health Care",
    "MCO": "Financials",
    "MDB": "Information Technology",
    "MDLZ": "Consumer Staples",
    "MDT": "Health Care",
    "MET": "Financials",
    "META": "Communication Services",
    "MGM": "Consumer Discretionary",
    "MHK": "Consumer Discretionary",
    "MKC": "Consumer Staples",
    "MKTX": "Financials",
    "MLM": "Materials",
    "MMC": "Financials",
    "MMM": "Industrials",
    "MNST": "Consumer Staples",
    "MO": "Consumer Staples",
    "MOH": "Health Care",
    "MOS": "Materials",
    "MPC": "Energy",
    "MPWR": "Information Technology",
    "MRK": "Health Care",
    "MRNA": "Health Care",
    "MRO": "Energy",
    "MRVL": "Information Technology",
    "MS": "Financials",
    "MSFT": "Information Technology",
    "MSI": "Information Technology",
    "MTB": "Financials",
    "MTCH": "Communication Services",
    "MTD": "Health Care",
    "MU": "Information Technology",
    "NCLH": "Consumer Discretionary",
    "NDAQ": "Financials",
    "NDSN": "Industrials",
    "NEE": "Utilities",
    "NEM": "Materials",
    "NET": "Information Technology",
    "NFLX": "Communication Services",
    "NI": "Utilities",
    "NKE": "Consumer Discretionary",
    "NNN": "Real Estate",
    "NOC": "Industrials",
    "NOW": "Information Technology",
    "NRG": "Utilities",
    "NSC": "Industrials",
    "NTAP": "Information Technology",
    "NTRS": "Financials",
    "NUE": "Materials",
    "NVDA": "Information Technology",
    "NVR": "Consumer Discretionary",
    "NWS": "Communication Services",
    "NWSA": "Communication Services",
    "NXPI": "Information Technology",
    "O": "Real Estate",
    "OKE": "Energy",
    "OKTA": "Information Technology",
    "OMC": "Communication Services",
    "OMF": "Financials",
    "ON": "Information Technology",
    "ORCL": "Information Technology",
    "ORLY": "Consumer Discretionary",
    "OTIS": "Industrials",
    "OVV": "Energy",
    "OXY": "Energy",
    "PANW": "Information Technology",
    "PARA": "Communication Services",
    "PAYC": "Information Technology",
    "PAYX": "Information Technology",
    "PCG": "Utilities",
    "PCTY": "Information Technology",
    "PDCO": "Health Care",
    "PEAK": "Real Estate",
    "PEGA": "Information Technology",
    "PENN": "Consumer Discretionary",
    "PEP": "Consumer Staples",
    "PFE": "Health Care",
    "PG": "Consumer Staples",
    "PH": "Industrials",
    "PHM": "Consumer Discretionary",
    "PINS": "Communication Services",
    "PKG": "Consumer Discretionary",
    "PLD": "Real Estate",
    "PM": "Consumer Staples",
    "PNC": "Financials",
    "PNW": "Utilities",
    "PODD": "Health Care",
    "POOL": "Industrials",
    "POR": "Utilities",
    "PPC": "Consumer Staples",
    "PPG": "Materials",
    "PRU": "Financials",
    "PSA": "Real Estate",
    "PSX": "Energy",
    "PVH": "Consumer Discretionary",
    "PWR": "Industrials",
    "PXD": "Energy",
    "PYPL": "Financials",
    "QCOM": "Information Technology",
    "QRVO": "Information Technology",
    "RCL": "Consumer Discretionary",
    "REG": "Real Estate",
    "REGN": "Health Care",
    "REXR": "Real Estate",
    "REYN": "Consumer Discretionary",
    "RF": "Financials",
    "RH": "Consumer Discretionary",
    "RHI": "Industrials",
    "RJF": "Financials",
    "RL": "Consumer Discretionary",
    "RMD": "Health Care",
    "RNG": "Information Technology",
    "ROK": "Industrials",
    "ROP": "Information Technology",
    "ROST": "Consumer Discretionary",
    "RPM": "Materials",
    "RS": "Materials",
    "RSG": "Industrials",
    "RTX": "Industrials",
    "SAIC": "Information Technology",
    "SBAC": "Real Estate",
    "SBUX": "Consumer Discretionary",
    "SCHW": "Financials",
    "SEE": "Consumer Discretionary",
    "SHW": "Materials",
    "SJM": "Consumer Staples",
    "SLB": "Energy",
    "SLM": "Financials",
    "SNA": "Industrials",
    "SNPS": "Information Technology",
    "SO": "Utilities",
    "SON": "Consumer Discretionary",
    "SPG": "Real Estate",
    "SPGI": "Financials",
    "SRCL": "Industrials",
    "SRE": "Utilities",
    "STE": "Health Care",
    "STLD": "Materials",
    "STT": "Financials",
    "STX": "Information Technology",
    "STZ": "Consumer Staples",
    "SUI": "Real Estate",
    "SWK": "Industrials",
    "SWKS": "Information Technology",
    "SYF": "Financials",
    "SYK": "Health Care",
    "SYY": "Consumer Staples",
    "T": "Communication Services",
    "TAP": "Consumer Staples",
    "TDG": "Industrials",
    "TDY": "Information Technology",
    "TEAM": "Information Technology",
    "TECH": "Health Care",
    "TER": "Information Technology",
    "TFC": "Financials",
    "THC": "Health Care",
    "TJX": "Consumer Discretionary",
    "TMO": "Health Care",
    "TMUS": "Communication Services",
    "TPR": "Consumer Discretionary",
    "TRGP": "Energy",
    "TRMB": "Information Technology",
    "TRNO": "Real Estate",
    "TROW": "Financials",
    "TRV": "Financials",
    "TSLA": "Consumer Discretionary",
    "TSN": "Consumer Staples",
    "TTWO": "Communication Services",
    "TXN": "Information Technology",
    "TXT": "Industrials",
    "TYL": "Information Technology",
    "UAL": "Industrials",
    "UDR": "Real Estate",
    "UE": "Real Estate",
    "UHS": "Health Care",
    "ULTA": "Consumer Discretionary",
    "UNH": "Health Care",
    "UNP": "Industrials",
    "UPS": "Industrials",
    "USB": "Financials",
    "V": "Financials",
    "VEEV": "Health Care",
    "VICI": "Real Estate",
    "VLO": "Energy",
    "VMC": "Materials",
    "VOYA": "Financials",
    "VRSK": "Industrials",
    "VRTX": "Health Care",
    "VST": "Utilities",
    "VTR": "Real Estate",
    "VTRS": "Health Care",
    "VZ": "Communication Services",
    "WAB": "Industrials",
    "WAT": "Health Care",
    "WBA": "Consumer Staples",
    "WBD": "Communication Services",
    "WDAY": "Information Technology",
    "WDC": "Information Technology",
    "WEC": "Utilities",
    "WELL": "Real Estate",
    "WFC": "Financials",
    "WHR": "Consumer Discretionary",
    "WM": "Industrials",
    "WMB": "Energy",
    "WMT": "Consumer Staples",
    "WPC": "Real Estate",
    "WTW": "Financials",
    "WYNN": "Consumer Discretionary",
    "XEL": "Utilities",
    "XOM": "Energy",
    "XPO": "Industrials",
    "XRAY": "Health Care",
    "XYL": "Industrials",
    "YUM": "Consumer Discretionary",
    "ZBH": "Health Care",
    "ZBRA": "Information Technology",
    "ZS": "Information Technology",
    "ZTS": "Health Care",
}

# Validate against the canonical taxonomy at import time.
from pipeline.sources.macro import SECTOR_ETFS as _SECTOR_ETFS
_VALID = set(_SECTOR_ETFS.keys())
_invalid = {t: s for t, s in TICKER_SECTORS.items() if s not in _VALID}
assert not _invalid, f"sector_map.py contains non-GICS sectors: {_invalid}"
