"""
tools/company_names.py

Hardcoded mapping of every ticker in the SentimentAPI universe to its
full company name (S&P 500 snapshot, April 2024).

Imported by tools/seed_company_names.py.
"""

COMPANY_NAMES: dict[str, str] = {
    # ── Communication Services ────────────────────────────────────────────────
    "GOOGL": "Alphabet Inc. (Class A)",
    "GOOG":  "Alphabet Inc. (Class C)",
    "META":  "Meta Platforms Inc.",
    "NFLX":  "Netflix Inc.",
    "DIS":   "The Walt Disney Co.",
    "CMCSA": "Comcast Corp.",
    "T":     "AT&T Inc.",
    "VZ":    "Verizon Communications Inc.",
    "CHTR":  "Charter Communications Inc.",
    "TMUS":  "T-Mobile US Inc.",
    "EA":    "Electronic Arts Inc.",
    "TTWO":  "Take-Two Interactive Software Inc.",
    "LYV":   "Live Nation Entertainment Inc.",
    "PARA":  "Paramount Global",
    "WBD":   "Warner Bros. Discovery Inc.",
    "IPG":   "Interpublic Group of Companies Inc.",
    "OMC":   "Omnicom Group Inc.",
    "FOXA":  "Fox Corp. (Class A)",
    "FOX":   "Fox Corp. (Class B)",
    "NWS":   "News Corp (Class B)",
    "NWSA":  "News Corp (Class A)",
    "MTCH":  "Match Group Inc.",
    "PINS":  "Pinterest Inc.",

    # ── Consumer Discretionary ────────────────────────────────────────────────
    "AMZN":  "Amazon.com Inc.",
    "TSLA":  "Tesla Inc.",
    "HD":    "The Home Depot Inc.",
    "MCD":   "McDonald's Corp.",
    "NKE":   "Nike Inc.",
    "LOW":   "Lowe's Companies Inc.",
    "SBUX":  "Starbucks Corp.",
    "TJX":   "TJX Companies Inc.",
    "BKNG":  "Booking Holdings Inc.",
    "CMG":   "Chipotle Mexican Grill Inc.",
    "GM":    "General Motors Co.",
    "F":     "Ford Motor Co.",
    "ORLY":  "O'Reilly Automotive Inc.",
    "AZO":   "AutoZone Inc.",
    "ROST":  "Ross Stores Inc.",
    "DLTR":  "Dollar Tree Inc.",
    "DHI":   "D.R. Horton Inc.",
    "LEN":   "Lennar Corp.",
    "PHM":   "PulteGroup Inc.",
    "NVR":   "NVR Inc.",
    "POOL":  "Pool Corp.",
    "GRMN":  "Garmin Ltd.",
    "LVS":   "Las Vegas Sands Corp.",
    "MGM":   "MGM Resorts International",
    "WYNN":  "Wynn Resorts Ltd.",
    "HLT":   "Hilton Worldwide Holdings Inc.",
    "MAR":   "Marriott International Inc.",
    "H":     "Hyatt Hotels Corp.",
    "CCL":   "Carnival Corp.",
    "RCL":   "Royal Caribbean Cruises Ltd.",
    "NCLH":  "Norwegian Cruise Line Holdings Ltd.",
    "YUM":   "Yum! Brands Inc.",
    "DPZ":   "Domino's Pizza Inc.",
    "ULTA":  "Ulta Beauty Inc.",
    "RH":    "RH",
    "BBWI":  "Bath & Body Works Inc.",
    "TPR":   "Tapestry Inc.",
    "RL":    "Ralph Lauren Corp.",
    "PVH":   "PVH Corp.",
    "MHK":   "Mohawk Industries Inc.",
    "WHR":   "Whirlpool Corp.",
    "LEG":   "Leggett & Platt Inc.",
    "APTV":  "Aptiv PLC",
    "CPRI":  "Capri Holdings Ltd.",
    "BWA":   "BorgWarner Inc.",
    "LKQ":   "LKQ Corp.",
    "DKNG":  "DraftKings Inc.",
    "PENN":  "PENN Entertainment Inc.",
    "CZR":   "Caesars Entertainment Inc.",
    "EXPE":  "Expedia Group Inc.",
    "EBAY":  "eBay Inc.",
    "ETSY":  "Etsy Inc.",
    "HAS":   "Hasbro Inc.",
    "MAT":   "Mattel Inc.",

    # ── Consumer Staples ──────────────────────────────────────────────────────
    "WMT":   "Walmart Inc.",
    "PG":    "Procter & Gamble Co.",
    "KO":    "Coca-Cola Co.",
    "PEP":   "PepsiCo Inc.",
    "COST":  "Costco Wholesale Corp.",
    "PM":    "Philip Morris International Inc.",
    "MO":    "Altria Group Inc.",
    "MDLZ":  "Mondelez International Inc.",
    "CL":    "Colgate-Palmolive Co.",
    "KMB":   "Kimberly-Clark Corp.",
    "GIS":   "General Mills Inc.",
    "HSY":   "Hershey Co.",
    "K":     "Kellanova",
    "SJM":   "J.M. Smucker Co.",
    "CPB":   "Campbell Soup Co.",
    "HRL":   "Hormel Foods Corp.",
    "MKC":   "McCormick & Co.",
    "CHD":   "Church & Dwight Co.",
    "CLX":   "Clorox Co.",
    "EL":    "Estee Lauder Companies Inc.",
    "MNST":  "Monster Beverage Corp.",
    "STZ":   "Constellation Brands Inc.",
    "TAP":   "Molson Coors Beverage Co.",
    "KDP":   "Keurig Dr Pepper Inc.",
    "KHC":   "Kraft Heinz Co.",
    "TSN":   "Tyson Foods Inc.",
    "CAG":   "Conagra Brands Inc.",
    "WBA":   "Walgreens Boots Alliance Inc.",
    "SYY":   "Sysco Corp.",
    "ADM":   "Archer-Daniels-Midland Co.",
    "BG":    "Bunge Global SA",
    "PPC":   "Pilgrim's Pride Corp.",
    "COTY":  "Coty Inc.",
    "REYN":  "Reynolds Consumer Products Inc.",

    # ── Energy ────────────────────────────────────────────────────────────────
    "XOM":   "Exxon Mobil Corp.",
    "CVX":   "Chevron Corp.",
    "COP":   "ConocoPhillips",
    "EOG":   "EOG Resources Inc.",
    "SLB":   "SLB",
    "MPC":   "Marathon Petroleum Corp.",
    "PSX":   "Phillips 66",
    "VLO":   "Valero Energy Corp.",
    "PXD":   "Pioneer Natural Resources Co.",
    "DVN":   "Devon Energy Corp.",
    "HAL":   "Halliburton Co.",
    "BKR":   "Baker Hughes Co.",
    "OXY":   "Occidental Petroleum Corp.",
    "APA":   "APA Corp.",
    "FANG":  "Diamondback Energy Inc.",
    "EQT":   "EQT Corp.",
    "MRO":   "Marathon Oil Corp.",
    "HES":   "Hess Corp.",
    "CTRA":  "Coterra Energy Inc.",
    "OVV":   "Ovintiv Inc.",
    "KMI":   "Kinder Morgan Inc.",
    "WMB":   "Williams Companies Inc.",
    "OKE":   "ONEOK Inc.",
    "TRGP":  "Targa Resources Corp.",
    "LNG":   "Cheniere Energy Inc.",

    # ── Financials ────────────────────────────────────────────────────────────
    "BRK.B": "Berkshire Hathaway Inc. (Class B)",
    "JPM":   "JPMorgan Chase & Co.",
    "V":     "Visa Inc.",
    "MA":    "Mastercard Inc.",
    "BAC":   "Bank of America Corp.",
    "WFC":   "Wells Fargo & Co.",
    "MS":    "Morgan Stanley",
    "GS":    "Goldman Sachs Group Inc.",
    "C":     "Citigroup Inc.",
    "AXP":   "American Express Co.",
    "BLK":   "BlackRock Inc.",
    "SPGI":  "S&P Global Inc.",
    "MCO":   "Moody's Corp.",
    "CB":    "Chubb Ltd.",
    "MMC":   "Marsh & McLennan Companies Inc.",
    "AON":   "Aon PLC",
    "SCHW":  "Charles Schwab Corp.",
    "FIS":   "Fidelity National Information Services Inc.",
    "FISV":  "Fiserv Inc.",
    "ICE":   "Intercontinental Exchange Inc.",
    "CME":   "CME Group Inc.",
    "NDAQ":  "Nasdaq Inc.",
    "TFC":   "Truist Financial Corp.",
    "USB":   "U.S. Bancorp",
    "PNC":   "PNC Financial Services Group Inc.",
    "COF":   "Capital One Financial Corp.",
    "AIG":   "American International Group Inc.",
    "MET":   "MetLife Inc.",
    "PRU":   "Prudential Financial Inc.",
    "ALL":   "Allstate Corp.",
    "AFL":   "Aflac Inc.",
    "TRV":   "Travelers Companies Inc.",
    "HIG":   "Hartford Financial Services Group Inc.",
    "RJF":   "Raymond James Financial Inc.",
    "NTRS":  "Northern Trust Corp.",
    "STT":   "State Street Corp.",
    "BK":    "Bank of New York Mellon Corp.",
    "CFG":   "Citizens Financial Group Inc.",
    "HBAN":  "Huntington Bancshares Inc.",
    "RF":    "Regions Financial Corp.",
    "KEY":   "KeyCorp",
    "MTB":   "M&T Bank Corp.",
    "FITB":  "Fifth Third Bancorp",
    "CINF":  "Cincinnati Financial Corp.",
    "WTW":   "Willis Towers Watson PLC",
    "EG":    "Everest Group Ltd.",
    "ALLY":  "Ally Financial Inc.",
    "SYF":   "Synchrony Financial",
    "DFS":   "Discover Financial Services",
    "MKTX":  "MarketAxess Holdings Inc.",
    "CBOE":  "Cboe Global Markets Inc.",
    "LPLA":  "LPL Financial Holdings Inc.",
    "AMG":   "Affiliated Managers Group Inc.",
    "BEN":   "Franklin Resources Inc.",
    "FHI":   "Federated Hermes Inc.",
    "TROW":  "T. Rowe Price Group Inc.",
    "AMP":   "Ameriprise Financial Inc.",
    "IVZ":   "Invesco Ltd.",
    "VOYA":  "Voya Financial Inc.",
    "OMF":   "OneMain Holdings Inc.",
    "SLM":   "SLM Corp.",
    "CACC":  "Credit Acceptance Corp.",

    # ── Health Care ───────────────────────────────────────────────────────────
    "UNH":   "UnitedHealth Group Inc.",
    "JNJ":   "Johnson & Johnson",
    "LLY":   "Eli Lilly & Co.",
    "ABBV":  "AbbVie Inc.",
    "MRK":   "Merck & Co. Inc.",
    "TMO":   "Thermo Fisher Scientific Inc.",
    "ABT":   "Abbott Laboratories",
    "DHR":   "Danaher Corp.",
    "PFE":   "Pfizer Inc.",
    "BMY":   "Bristol-Myers Squibb Co.",
    "AMGN":  "Amgen Inc.",
    "ISRG":  "Intuitive Surgical Inc.",
    "SYK":   "Stryker Corp.",
    "MDT":   "Medtronic PLC",
    "BSX":   "Boston Scientific Corp.",
    "GEHC":  "GE HealthCare Technologies Inc.",
    "EW":    "Edwards Lifesciences Corp.",
    "ZBH":   "Zimmer Biomet Holdings Inc.",
    "HOLX":  "Hologic Inc.",
    "BAX":   "Baxter International Inc.",
    "BDX":   "Becton Dickinson & Co.",
    "COO":   "Cooper Companies Inc.",
    "RMD":   "ResMed Inc.",
    "PODD":  "Insulet Corp.",
    "DXCM":  "DexCom Inc.",
    "IDXX":  "IDEXX Laboratories Inc.",
    "MTD":   "Mettler-Toledo International Inc.",
    "WAT":   "Waters Corp.",
    "A":     "Agilent Technologies Inc.",
    "ALGN":  "Align Technology Inc.",
    "VTRS":  "Viatris Inc.",
    "ZTS":   "Zoetis Inc.",
    "VRTX":  "Vertex Pharmaceuticals Inc.",
    "REGN":  "Regeneron Pharmaceuticals Inc.",
    "GILD":  "Gilead Sciences Inc.",
    "BIIB":  "Biogen Inc.",
    "MRNA":  "Moderna Inc.",
    "ILMN":  "Illumina Inc.",
    "IQV":   "IQVIA Holdings Inc.",
    "MCK":   "McKesson Corp.",
    "ABC":   "Cencora Inc.",
    "CAH":   "Cardinal Health Inc.",
    "CI":    "Cigna Group",
    "CVS":   "CVS Health Corp.",
    "HUM":   "Humana Inc.",
    "CNC":   "Centene Corp.",
    "MOH":   "Molina Healthcare Inc.",
    "ELV":   "Elevance Health Inc.",
    "UHS":   "Universal Health Services Inc.",
    "HCA":   "HCA Healthcare Inc.",
    "THC":   "Tenet Healthcare Corp.",
    "DVA":   "DaVita Inc.",
    "HSIC":  "Henry Schein Inc.",
    "PDCO":  "Patterson Companies Inc.",
    "INCY":  "Incyte Corp.",
    "EXAS":  "Exact Sciences Corp.",
    "STE":   "STERIS PLC",
    "XRAY":  "Dentsply Sirona Inc.",
    "TECH":  "Bio-Techne Corp.",
    "AMED":  "Amedisys Inc.",

    # ── Industrials ───────────────────────────────────────────────────────────
    "RTX":   "RTX Corp.",
    "HON":   "Honeywell International Inc.",
    "UNP":   "Union Pacific Corp.",
    "CAT":   "Caterpillar Inc.",
    "DE":    "Deere & Co.",
    "GE":    "GE Aerospace",
    "MMM":   "3M Co.",
    "LMT":   "Lockheed Martin Corp.",
    "BA":    "Boeing Co.",
    "NOC":   "Northrop Grumman Corp.",
    "GD":    "General Dynamics Corp.",
    "LHX":   "L3Harris Technologies Inc.",
    "TXT":   "Textron Inc.",
    "HWM":   "Howmet Aerospace Inc.",
    "TDG":   "TransDigm Group Inc.",
    "LDOS":  "Leidos Holdings Inc.",
    "SAIC":  "Science Applications International Corp.",
    "CARR":  "Carrier Global Corp.",
    "OTIS":  "Otis Worldwide Corp.",
    "ETN":   "Eaton Corp. PLC",
    "EMR":   "Emerson Electric Co.",
    "ROK":   "Rockwell Automation Inc.",
    "IR":    "Ingersoll Rand Inc.",
    "XYL":   "Xylem Inc.",
    "AME":   "AMETEK Inc.",
    "ROP":   "Roper Technologies Inc.",
    "FTV":   "Fortive Corp.",
    "GNRC":  "Generac Holdings Inc.",
    "FAST":  "Fastenal Co.",
    "SNA":   "Snap-on Inc.",
    "PH":    "Parker-Hannifin Corp.",
    "ITW":   "Illinois Tool Works Inc.",
    "DOV":   "Dover Corp.",
    "GWW":   "W.W. Grainger Inc.",
    "SWK":   "Stanley Black & Decker Inc.",
    "FLS":   "Flowserve Corp.",
    "IEX":   "IDEX Corp.",
    "NDSN":  "Nordson Corp.",
    "ALLE":  "Allegion PLC",
    "UPS":   "United Parcel Service Inc.",
    "FDX":   "FedEx Corp.",
    "JBHT":  "J.B. Hunt Transport Services Inc.",
    "XPO":   "XPO Inc.",
    "CHRW":  "C.H. Robinson Worldwide Inc.",
    "EXPD":  "Expeditors International of Washington Inc.",
    "CSX":   "CSX Corp.",
    "NSC":   "Norfolk Southern Corp.",
    "WAB":   "Westinghouse Air Brake Technologies Corp.",
    "DAL":   "Delta Air Lines Inc.",
    "UAL":   "United Airlines Holdings Inc.",
    "AAL":   "American Airlines Group Inc.",
    "LUV":   "Southwest Airlines Co.",
    "ALK":   "Alaska Air Group Inc.",
    "CTAS":  "Cintas Corp.",
    "PAYX":  "Paychex Inc.",
    "ADP":   "Automatic Data Processing Inc.",
    "WM":    "Waste Management Inc.",
    "RSG":   "Republic Services Inc.",
    "SRCL":  "Stericycle Inc.",
    "HII":   "Huntington Ingalls Industries Inc.",
    "TDY":   "Teledyne Technologies Inc.",
    "AXON":  "Axon Enterprise Inc.",
    "RHI":   "Robert Half Inc.",
    "CPRT":  "Copart Inc.",
    "VRSK":  "Verisk Analytics Inc.",
    "EFX":   "Equifax Inc.",
    "AOS":   "A.O. Smith Corp.",
    "HUBB":  "Hubbell Inc.",
    "PWR":   "Quanta Services Inc.",
    "AGCO":  "AGCO Corp.",
    "CNH":   "CNH Industrial NV",
    "ACM":   "AECOM",
    "J":     "Jacobs Solutions Inc.",

    # ── Information Technology ────────────────────────────────────────────────
    "AAPL":  "Apple Inc.",
    "MSFT":  "Microsoft Corp.",
    "NVDA":  "NVIDIA Corp.",
    "AVGO":  "Broadcom Inc.",
    "ORCL":  "Oracle Corp.",
    "CRM":   "Salesforce Inc.",
    "ACN":   "Accenture PLC",
    "AMD":   "Advanced Micro Devices Inc.",
    "QCOM":  "Qualcomm Inc.",
    "INTC":  "Intel Corp.",
    "IBM":   "International Business Machines Corp.",
    "AMAT":  "Applied Materials Inc.",
    "MU":    "Micron Technology Inc.",
    "ADI":   "Analog Devices Inc.",
    "KLAC":  "KLA Corp.",
    "LRCX":  "Lam Research Corp.",
    "NOW":   "ServiceNow Inc.",
    "INTU":  "Intuit Inc.",
    "TXN":   "Texas Instruments Inc.",
    "CDNS":  "Cadence Design Systems Inc.",
    "MCHP":  "Microchip Technology Inc.",
    "NXPI":  "NXP Semiconductors NV",
    "FTNT":  "Fortinet Inc.",
    "PANW":  "Palo Alto Networks Inc.",
    "HPE":   "Hewlett Packard Enterprise Co.",
    "HPQ":   "HP Inc.",
    "DELL":  "Dell Technologies Inc.",
    "GLW":   "Corning Inc.",
    "CSCO":  "Cisco Systems Inc.",
    "SNPS":  "Synopsys Inc.",
    "ANSS":  "Ansys Inc.",
    "ADBE":  "Adobe Inc.",
    "AKAM":  "Akamai Technologies Inc.",
    "CDW":   "CDW Corp.",
    "STX":   "Seagate Technology Holdings PLC",
    "WDC":   "Western Digital Corp.",
    "NTAP":  "NetApp Inc.",
    "KEYS":  "Keysight Technologies Inc.",
    "TRMB":  "Trimble Inc.",
    "ENPH":  "Enphase Energy Inc.",
    "FSLR":  "First Solar Inc.",
    "MPWR":  "Monolithic Power Systems Inc.",
    "ON":    "ON Semiconductor Corp.",
    "TER":   "Teradyne Inc.",
    "SWKS":  "Skyworks Solutions Inc.",
    "QRVO":  "Qorvo Inc.",
    "MRVL":  "Marvell Technology Inc.",
    "ANET":  "Arista Networks Inc.",
    "FFIV":  "F5 Inc.",
    "JNPR":  "Juniper Networks Inc.",
    "ZBRA":  "Zebra Technologies Corp.",
    "APH":   "Amphenol Corp.",
    "MSI":   "Motorola Solutions Inc.",
    "EPAM":  "EPAM Systems Inc.",
    "FI":    "Fiserv Inc.",
    "GPN":   "Global Payments Inc.",
    "PYPL":  "PayPal Holdings Inc.",
    "NET":   "Cloudflare Inc.",
    "OKTA":  "Okta Inc.",
    "DDOG":  "Datadog Inc.",
    "CRWD":  "CrowdStrike Holdings Inc.",
    "ZS":    "Zscaler Inc.",
    "MDB":   "MongoDB Inc.",
    "VEEV":  "Veeva Systems Inc.",
    "WDAY":  "Workday Inc.",
    "TEAM":  "Atlassian Corp.",
    "GDDY":  "GoDaddy Inc.",
    "CTSH":  "Cognizant Technology Solutions Corp.",
    "DXC":   "DXC Technology Co.",
    "PAYC":  "Paycom Software Inc.",
    "PCTY":  "Paylocity Holding Corp.",
    "RNG":   "RingCentral Inc.",
    "PEGA":  "Pegasystems Inc.",
    "TYL":   "Tyler Technologies Inc.",
    "BLKB":  "Blackbaud Inc.",

    # ── Materials ─────────────────────────────────────────────────────────────
    "LIN":   "Linde PLC",
    "APD":   "Air Products & Chemicals Inc.",
    "SHW":   "Sherwin-Williams Co.",
    "ECL":   "Ecolab Inc.",
    "PPG":   "PPG Industries Inc.",
    "NEM":   "Newmont Corp.",
    "FCX":   "Freeport-McMoRan Inc.",
    "NUE":   "Nucor Corp.",
    "STLD":  "Steel Dynamics Inc.",
    "RS":    "Reliance Inc.",
    "CMC":   "Commercial Metals Co.",
    "AL":    "Air Lease Corp.",
    "AA":    "Alcoa Corp.",
    "MLM":   "Martin Marietta Materials Inc.",
    "VMC":   "Vulcan Materials Co.",
    "CRH":   "CRH PLC",
    "EXP":   "Eagle Materials Inc.",
    "PKG":   "Packaging Corp. of America",
    "IP":    "International Paper Co.",
    "SEE":   "Sealed Air Corp.",
    "AVY":   "Avery Dennison Corp.",
    "IFF":   "International Flavors & Fragrances Inc.",
    "EMN":   "Eastman Chemical Co.",
    "CE":    "Celanese Corp.",
    "HUN":   "Huntsman Corp.",
    "RPM":   "RPM International Inc.",
    "FMC":   "FMC Corp.",
    "MOS":   "Mosaic Co.",
    "CF":    "CF Industries Holdings Inc.",
    "ALB":   "Albemarle Corp.",
    "BALL":  "Ball Corp.",
    "SON":   "Sonoco Products Co.",
    "AMCR":  "Amcor PLC",
    "ATI":   "ATI Inc.",

    # ── Real Estate ───────────────────────────────────────────────────────────
    "PLD":   "Prologis Inc.",
    "AMT":   "American Tower Corp.",
    "EQIX":  "Equinix Inc.",
    "SPG":   "Simon Property Group Inc.",
    "WELL":  "Welltower Inc.",
    "DLR":   "Digital Realty Trust Inc.",
    "O":     "Realty Income Corp.",
    "PSA":   "Public Storage",
    "VICI":  "VICI Properties Inc.",
    "EQR":   "Equity Residential",
    "AVB":   "AvalonBay Communities Inc.",
    "MAA":   "Mid-America Apartment Communities Inc.",
    "UDR":   "UDR Inc.",
    "CPT":   "Camden Property Trust",
    "ESS":   "Essex Property Trust Inc.",
    "BXP":   "BXP Inc.",
    "ARE":   "Alexandria Real Estate Equities Inc.",
    "VTR":   "Ventas Inc.",
    "PEAK":  "Healthpeak Properties Inc.",
    "KIM":   "Kimco Realty Corp.",
    "REG":   "Regency Centers Corp.",
    "FRT":   "Federal Realty Investment Trust",
    "NNN":   "NNN REIT Inc.",
    "WPC":   "W. P. Carey Inc.",
    "SBAC":  "SBA Communications Corp.",
    "CCI":   "Crown Castle Inc.",
    "SUI":   "Sun Communities Inc.",
    "ELS":   "Equity LifeStyle Properties Inc.",
    "UE":    "Urban Edge Properties",
    "CUBE":  "CubeSmart",
    "LSI":   "Life Storage Inc.",
    "REXR":  "Rexford Industrial Realty Inc.",
    "TRNO":  "Terreno Realty Corp.",
    "EGP":   "EastGroup Properties Inc.",
    "FR":    "First Industrial Realty Trust Inc.",

    # ── Utilities ─────────────────────────────────────────────────────────────
    "NEE":   "NextEra Energy Inc.",
    "DUK":   "Duke Energy Corp.",
    "SO":    "Southern Co.",
    "D":     "Dominion Energy Inc.",
    "AEP":   "American Electric Power Co.",
    "SRE":   "Sempra Energy",
    "PCG":   "PG&E Corp.",
    "EXC":   "Exelon Corp.",
    "ED":    "Consolidated Edison Inc.",
    "WEC":   "WEC Energy Group Inc.",
    "ES":    "Eversource Energy",
    "XEL":   "Xcel Energy Inc.",
    "ETR":   "Entergy Corp.",
    "FE":    "FirstEnergy Corp.",
    "CMS":   "CMS Energy Corp.",
    "LNT":   "Alliant Energy Corp.",
    "NI":    "NiSource Inc.",
    "EVRG":  "Evergy Inc.",
    "AES":   "AES Corp.",
    "PNW":   "Pinnacle West Capital Corp.",
    "POR":   "Portland General Electric Co.",
    "DTE":   "DTE Energy Co.",
    "CEG":   "Constellation Energy Corp.",
    "VST":   "Vistra Corp.",
    "NRG":   "NRG Energy Inc.",
    "AWK":   "American Water Works Co.",
    "AWR":   "American States Water Co.",
}
